spring:
  application:
    name: intergalactic-marketplace
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

application:
  feature:
    toggles:
      cosmoCats: true
      kittyProducts: false